name: Django CI/CD

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Клонування репозиторію
      uses: actions/checkout@v3

    - name: Встановлення Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Встановлення залежностей
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt

    - name: Застосування міграцій
      run: |
        source venv/bin/activate
        python manage.py migrate

    - name: Запуск тестів
      run: |
        source venv/bin/activate
        python manage.py test
"" 
